# Generated by Django 5.1.7 on 2025-04-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward_no',
            name='name',
            field=models.CharField(max_length=3),
        ),
    ]
